language: php
php:
  - 5.6
before_install:
  - composer install
matrix:
  allow_failures:
  - php: 5.6
env:
  - MAGENTO_VERSION=magento-ce-1.9.4.2
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - me@laurafolco.com
    on_success: always
    on_failure: always
